[package]
authors = ["Damir Jelić <poljar@termina.org.uk>"]
description = "Implementation of the FLOE cryptographic construction"
name = "floe-rs"
version = "0.1.0"
edition = "2024"
keywords = ["cryptography", "floe", "online-encryption", "random-access"]
license = "Apache-2.0"
repository = "https://github.com/poljar/floe"
rust-version = "1.93"

exclude = ["test-vectors/*", ".github/*", ".config/*", "justfile"]

[features]
default = ["std", "floe-gcm", "getrandom", "zeroize"]

std = ["thiserror/std"]
floe-gcm = ["dep:aes-gcm", "dep:sha2"]
getrandom = ["dep:getrandom"]
zeroize = ["dep:zeroize"]

[dependencies]
aead = "0.6.1"
aes-gcm = { version = "0.11.0", optional = true, default-features = false, features = ["aes"] }
digest = { version = "0.11.3", features = ["mac"] }
getrandom = { version = "0.4.3", optional = true, features = ["sys_rng"] }
hkdf = "0.13.0"
hybrid-array = { version = "0.4.14", features = ["zerocopy"] }
itertools = "0.15.0"
rand_core = "0.10.1"
sha2 = { version = "0.11.0", optional = true }
subtle = "2.6.1"
thiserror = { version = "2.0.20", default-features = false }
zerocopy = { version = "0.8.56", features = ["derive"] }
zeroize = { version = "1.9.0", optional = true, features = ["zeroize_derive"] }

[dev-dependencies]
anyhow = "1.0.104"
hex = "0.4.3"
pastey = "0.2.3"

[lints.rust]
dead_code = "deny"
# missing_docs = "deny"
rust_2018_idioms = "deny"
trivial_casts = "deny"
trivial_numeric_casts = "deny"
unexpected_cfgs = { level = "deny", check-cfg = ['cfg(fuzzing)'] }
unused_extern_crates = "deny"
unused_import_braces = "deny"
unused_qualifications = "deny"
unreachable_pub = "deny"
unsafe_code = "deny"
unsafe_op_in_unsafe_fn = "deny"

[lints.clippy]
cast_lossless = "deny"
cast_possible_truncation = "deny"
cast_possible_wrap = "deny"
cast_sign_loss = "deny"
dbg_macro = "deny"
empty_docs = "deny"
empty_line_after_doc_comments = "deny"
expect_used = "deny"
mem_forget = "deny"
# missing_docs_in_private_items = "deny"
missing_errors_doc = "deny"
missing_panics_doc = "deny"
panic = "deny"
std_instead_of_core = "deny"
std_instead_of_alloc = "deny"
todo = "deny"
too_long_first_doc_paragraph = "deny"
unreachable = "deny"
unwrap_used = "deny"
